- name: Create file using my_own_module
  my_own_namespace.yandex_cloud_elk.my_own_module:
    path: "{{ my_module_path }}"
    content: "{{ my_module_content }}"
    owner: "{{ my_module_owner }}"
    group: "{{ my_module_group }}"
    mode: "{{ my_module_mode }}"
    backup: "{{ my_module_backup }}"
  register: my_module_result

- name: Show module result
  debug:
    var: my_module_result
  when: my_module_result.changed
