all:
  children:
    webservers:
      hosts:
        web-1:
          ansible_host: 93.77.189.0
          fqdn: web-1.ru-central1.internal
        web-2:
          ansible_host: 93.77.182.0
          fqdn: web-2.ru-central1.internal
    databases:
      hosts:
        db-main:
          ansible_host: 93.77.176.229
          fqdn: db-main.ru-central1.internal
        db-replica:
          ansible_host: 89.169.149.144
          fqdn: db-replica.ru-central1.internal
    storage:
      hosts:
        storage:
          ansible_host: 93.77.178.207
          fqdn: storage.ru-central1.internal
    all:vars:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa