---
driver:
  name: docker

platforms:
  - name: vector-ubuntu
    image: ubuntu:22.04
    pre_build_image: true
    privileged: true
    command: sleep infinity
    # 🔧 Укажите интерпретатор Python3
    ansible_connection: docker
    ansible_python_interpreter: /usr/bin/python3

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  env:
    ANSIBLE_ROLES_PATH: ../../

verifier:
  name: ansible
