apiVersion: v1
kind: Service
metadata:
  name: task1-service
spec:
  selector:
    app: task1
  ports:
  - name: nginx
    port: 9001
    targetPort: 80
  - name: multitool
    port: 9002
    targetPort: 8080
  type: ClusterIP