FROM python:3.12-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    mysql-connector-python \
    pymysql
EXPOSE 5000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
