# Используем базовый образ python:3.12-slim
FROM python:3.12-slim
# Устанавливаем рабочую директорию
WORKDIR /app
# Копируем зависимости и устанавливаем их
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Копируем весь код приложения
COPY . .
# Запускаем приложение через uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]