---
namespace: my_own_namespace
name: yandex_cloud_elk
version: 1.0.0
readme: README.md
authors:
  - Anastasia Andryushina (@Nastil2019)
description: Custom collection with my_own_module
license:
  - GPL-3.0-or-later
tags:
  - custom_module
  - files
dependencies: {}
repository: https://github.com/Nastil2019/my_own_collection
build_ignore:
  - '*.tar.gz'
  - '.git'
  - 'venv'
